### ISSUE TITLE
How do I change to desktop view of website?

### ISSUE THREAD

**Issue by SteelyxYT** [threethan/LightningBrowser#7]
I am using the browser for spotify and when I first lauched the browser it lauched in desktop mode. Now its only launching in phone mode and will ask alot about spotify premium. Is there a way to change it because I can't see any option menu for it.

**Comment by threethan** [comment]
Most websites request the desktop site. Spotify is the sole exception - The desktop site has some major issues on GeckoView. It sometimes works on "first-try" but then refuses to play anything after being reloaded. 

Lightning Browser requests the mobile version of spotify, and includes a built-in extension that slightly enhances the mobile version of the spotify website.

I know this isn't ideal, but the incompatibility between Spotify and GeckoView is not specific to Lightning Browser; even though the workaround is.

**Comment by SteelyxYT** [comment]
I got spotify to open in desktop mode just by being logged inn and requesting spotify.com instead of app.spotify.com
